<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7158" started-at="2017-09-15T03:37:36Z" finished-at="2017-09-15T03:37:43Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7158" started-at="2017-09-15T03:37:36Z" finished-at="2017-09-15T03:37:43Z">
      <class name="com.orion.whitemartProject.testScripts.TCOO1_testLogin">
        <test-method status="FAIL" signature="setup()[pri:0, instance:com.orion.whitemartProject.testScripts.TCOO1_testLogin@28d25987]" name="setup" is-config="true" duration-ms="0" started-at="2017-09-15T15:37:36Z" finished-at="2017-09-15T15:37:36Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.orion.whitemartProject.testBase.TestBase.init(TestBase.java:28)
	at com.orion.whitemartProject.testScripts.TCOO1_testLogin.setup(TCOO1_testLogin.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="SKIP" signature="testRegistrationWithInValidData()[pri:0, instance:com.orion.whitemartProject.testScripts.TCOO1_testLogin@28d25987]" name="testRegistrationWithInValidData" duration-ms="3" started-at="2017-09-15T15:37:43Z" description="Test Registration with valid data" finished-at="2017-09-15T15:37:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRegistrationWithInValidData -->
      </class> <!-- com.orion.whitemartProject.testScripts.TCOO1_testLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
